sudo: required
dist: trusty
language: node_js
node_js:
  - stable
branches:
  except:
    - gh-pages
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script: yarn add polymer-cli
script:
  - xvfb-run wct --module-resolution=node --npm --skip-plugin sauce
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --module-resolution=node --npm --plugin sauce --skip-plugin local; fi'
after_success:
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET" -in deploy.enc -out deploy_key -d; fi'
  - cd $TRAVIS_BUILD_DIR/scripts
  - chmod 755 ghp.sh
  - ./ghp.sh
env:
  global:
    - secure: krjg3I5esUxezO3ImKbZ8KGTfr6q8d3gL3m+vu6BXAVky9B2z5+iUe8j6j2XlzSNFi/HYWhYxsWdfacMXag93bbkmKlzBOyRkpHtQVmAevqLNrrlZ6XdBKqh/J1f9+g/OdWIOsLPG9faXVwr98xSb2QpDu/NuRC/La8ZAOh2OVpFej/ZgYujnqm9mk7STTzzeqaTLGqbOHtsMlSJd08Z5ZwLrdtafn5BE/QOdwPusYOPI3b+Zatp6ghZNZS6sHVDKzA/YIzHixBtB4Vao4vbX7G6lzvLcAxh9jz6U+lC2pd3+kqwXUX58iYT/2iRG04f8QHEUzPPheJ+ETJUrrg0XxJ7x4EwxBi3bvaVLA9XmFRXtwqKKiRRTgvL8yVteTGAXsJYfkrlx4Uu9za7jnK6tcEpZUD/Bkd9wn/6XcePIYkTM39U9esh1XzfZzw+U2jwiC9ASAxS4dNYGlgYvtLaFUhTi2KKHuXIfpWuJfWT33WiiDU0Lhy6rLmB1JRMX1lUnO++Om0PjDv6IfEpFdpuVLtKgQgCk73TGj5iwpLMJ2utKecew6gUdad4Q611XFVVaEbhHOMcy69v1yxor+EKpKFOuRbqdfM3L3TJGkrOty2er/AmOpfqPePB7HCZopr9XTq9Kv05+17ja1CIgCymEl6z4IbZG7BcRhMK4GwjrNM=
    - secure: rgROOMjn8dOpc3nGFqeJwOS8vx87OM0VugtlatfT30PWLwX65KuH9itPmRBoAHw8As3xQ9mLdO7qCOIN85v8kW2CJ7HKOpneh4RPc+O2uobTWa2TjS9TL+v3jbMIxYvZ/V5ncxIIzyrvv+0yVhyrzQsYTJRUGB794ehplfqhFlJBFMf/tR1s7NPey1r5PGiAH8h8+RoZq/pS0CZB9OkiT5AXya0/ANzoPxvLUWm1wA+eQHKlMIVLLxWNzprg67DFm4rPS1apzWo54XeN3Ovpdzexj0Q2qpCU23F77q+ync6Z/APhj+N0u3wvNRWlhzhIRClV0BGdgb31gjKeEOnxZbHPt7Iez5ZLQ1XG5pzWPUjUIPesfDyc6scC2b8CTq6VOHTW+g9q4R8GX4iwJl3/zYQwS9c7juIoNsF6+bYPiVRfm+VaFUXdW3XonqzFdFhpZDmjsSuHyAiw7eEGoyfkS3Mrnh5RB0u7i6i0LjgZT7MoCtUk+xXurgfM9l/9IKAF+yC1HUkYJET3LLHCtqVWd4zTKdvYCyYmqnYltNf7sYsqsXSGZxz4pGNbFxRrI6ZE10LB9KoNMncmztmgVGFrWWwT+cQL+fwy3ysaY2MKXpEOKguAfNDWRaucisxdDttMY/iRqJdu4b3UgYXh7awczWJSPKnDWKvaJj0G8B6h158=
    - secure: nfDQYVOKv1Bh9ihBRUToRmz0lbflpWYyUazNxEV5EiaTs6kPTpCNSJYMdXLgGmr+mjv5HfEdVyJlUj5FzNPsgEi1YL0SXIOiYFsSPxtOfh3aOLlMj5gW+iitcHCxVPqSq6IrbL9Vkpg8MSBLpBVp8QbERa0i4IOuUA2MUCLOiIUQ8hXqN8z89/OYA7bNy6T4pKiQowVzzdSFNrUniYvp4zxReNTaDyrHw9Cg/lF0YbzDYJUjDKj8o3OQQVXgVhmzUX/Zr0ec6pKEv/QClvPj1Fvqca9H2ab4t/8eQvsLPhz/ulbzfSTEYFs3ADOkA1MwopNQBOXp4cbcLcfijGgZz8dqenbdJcrgpPZeT/xgKJWczK4GawowbF9dgbDsLOxjieGIjQsIAYBwOIxVsTWqkAQhW9aQhWPnTkuNDu3Cm/Ox30GuKF8a0WSVHd72Xc9eC8xcM2f6MIbQtZjRIZY3O9T7UC+koKBFB6sol3NaZS+9VN8wPG382aNpjosWB9k3QR3ORHuq7gy68abKQCBflS1Ikjk6NbNDIW3NyrwE9nKU6c8Bgn/hi0leD84JY0OrkusHHeQ51T90rBnR/+AUVXABW1OKm3Imm7cn8w1dvqdO62wEpsnrs7l4DfihBKExVpriPm5fJSY3GRNW9SuzEZN37Ft15bY3xMpWdtzUyRY=
    - secure: lWnQFDlJGaiyvootvbO2+z+0gVL2NILDHdNRbWM6NrgnbRtENfAID3Ek2knA3dbIHfEMpcjl4soYEHLuNDh1D7bZQzs7kvdSy6Yy2tXpwn/MshqMarK7a9rxLhLPTX8OuO+WGXT3D8jkUwDW5yex4qvJ1yT16bTRufPU8ZcYWIEv6wOYl2liW6PSE0rL/inEb1iGlP4q53SiVJNIjb4VKt+4u/M/skAsRe6UR9n1FwQqRWZrFiE4MdUYmua16cjYulMsrZ8+RzTDK2UvDRodF6a0nR7AtZln8AQDcLWEVt3Up1wJ83AaW2Ckt8CtVGL6sF5jKEwpbGhFGZrizEUEm7mClcx389KMJAIFsFqSAeA+ve6fbEf3kTodcFEOHSSFG+dLacKv5L7YPA/6ZNeszu6iB4gNRKwha/psIlgrGisEzy/qy2u0Oa8zMwJsQD9jyaxgM041wTm2eSK8cT2TRKNOIONAcLcinXTu5MTCx0FCG5VaF+nMXG/oUKS/w6b/6ynU0UvbgLsC2mb6d6Wm9KPi8Z3O3D6ErTaocbUxvqR/0Hv21x7IYTAOZhxhCtxcTyNgXXW7/Ve1SVsuMtFg2+87KlPZOWEWFF+2yzgalUg9imDt9wRwdJFOEP5nbeeQXsFI1K6PAQ41zkfXQYnjnjt5nJQ9UdVFugTDDcUgBL4=

